[package]
name = "example"
version = "0.1.0"
authors = ["zekin <wzekin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
model_macro = { path = "../macro" }
network = { path = "../." }
nalgebra = "0.19"
